apiVersion: v1
kind: Service
metadata:
  name: polygon-node
  namespace: rpcaas
  labels:
    app: polygon-node
    chain: polygon
spec:
  type: {{ .Values.service.type }}
  selector:
    app: polygon-node
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.bor.ports.rpc }}
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: {{ .Values.bor.ports.ws }}
      protocol: TCP
