apiVersion: v1
kind: Service
metadata:
  name: ethereum-node
  namespace: rpcaas
  labels:
    app: ethereum-node
    chain: ethereum
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ethereum-node
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.geth.ports.rpc }}
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: {{ .Values.geth.ports.ws }}
      protocol: TCP
