apiVersion: v1
kind: Service
metadata:
  name: optimism-node
  namespace: rpcaas
  labels:
    app: optimism-node
    chain: optimism
spec:
  type: {{ .Values.service.type }}
  selector:
    app: optimism-node
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.opGeth.ports.rpc }}
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: {{ .Values.opGeth.ports.ws }}
      protocol: TCP
