apiVersion: v1
kind: Service
metadata:
  name: arbitrum-node
  namespace: rpcaas
  labels:
    app: arbitrum-node
    chain: arbitrum
spec:
  type: {{ .Values.service.type }}
  selector:
    app: arbitrum-node
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.nitro.ports.rpc }}
      protocol: TCP
    - name: ws
      port: 8548
      targetPort: {{ .Values.nitro.ports.ws }}
      protocol: TCP
